  
-   id: commit-msg-regex-hook
    name: commit-msg-regex-hook
    description: Checks if commit message matches the passed in regex
    entry: commit-msg-regex-hook
    language: python
    types: [text]
